version: '3'

services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true  #for windows to other wise react won't detect changes
    stdin_open: true  #for new react app version issue
    build: 
      context: . #to find all the files from current all the directories if not in current directory go with => ./folder-name
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true  #for windows to other wise react won't detect changes
    stdin_open: true  #for new react app version issue
    build: 
      context: . #to find all the files from current all the directories if not in current directory go with => ./folder-name
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]